
name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{matrix.os}}
    defaults:
      run:
       working-directory: emotion_tracker/
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: emotion_tracker/package-lock.json
    - name: install dependencies
      run: npm i
    - name: Unit tests
      working-directory: emotion_tracker/src/
      run: npm test
    - name: Deploy
      uses: Lor3wp/NokiaHqEmotionTracker@v3
     # If you're changing the branch from main,
     # also change the `main` in `refs/heads/main`  
     # below accordingly.
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
